DIN_test:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 3
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null
    model: DIN
    dataset_id: ml-1m
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 32
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_hidden_units: [64]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0
    din_target_field: movie_id
    din_sequence_field: history_seq
    feature_specs: [{name: history_seq, feature_encoder: null}]
    net_dropout: 0
    batch_norm: False
    epochs: 50
    shuffle: True
    seed: 42
    monitor: 'AUC'
    monitor_mode: 'max'
    gpu: 0
    