taobao:
    data_root: '/home/liqun03/FuxiCTR/my_datasets'
    train_data: '/home/liqun03/FuxiCTR/my_datasets/taobao/train.parquet'
    valid_data: '/home/liqun03/FuxiCTR/my_datasets/taobao/valid.parquet'
    test_data: '/home/liqun03/FuxiCTR/my_datasets/taobao/test.parquet'