Base:
    model_root: './checkpoints/'
    num_workers: 4
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null


SIM_default: # This is a config template
    model: SIM

    dataset_id: ml-1m
    shuffle: True
    batch_size: 8192

    embedding_regularizer: 0
    net_regularizer: 0
    embedding_dim: 32
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_dim: 32
    num_heads: 2
    gsu_type: "soft"
    alpha: 1
    beta: 1
    attention_dropout: 0
    topk: 50
    short_seq_len: 50
    net_dropout: 0
    batch_norm: False

    loss: 'binary_crossentropy'
    metrics: [AUC, logloss]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    epochs: 100
    seed: 42

    monitor: 'AUC'
    monitor_mode: 'max'
    accumulation_steps: 1
    gpu: 0
