DIN: # This is a config template
    model: DIN

    dataset_id: ml-1m
    shuffle: True
    batch_size: 8192
    num_workers: 4

    model_root: './checkpoints/'
    embedding_regularizer: 0
    net_regularizer: 0
    embedding_dim: 32
    dnn_hidden_units: [120, 64]
    dnn_activations: relu
    attention_hidden_units: [64]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0
    din_use_softmax: False
    net_dropout: 0
    batch_norm: False

    verbose: 1
    loss: 'binary_crossentropy'
    metrics: [AUC, logloss]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    epochs: 100
    seed: 42
    # monitor: {'AUC': 1, 'logloss': -1}
    monitor: 'AUC'
    monitor_mode: 'max'
    accumulation_steps: 1
    gpu: 0
